language: ruby
rvm:
- 2.6.3
services:
  - postgresql
env:
  - DB=pgsql
before_script:
  - psql -c 'create database test18_test;' -U postgres
script:
  - bundle exec rake db:setup
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake spec