default: &default
  adapter: pg
  encoding: utf8mb4
  pool: 5
  host: localhost
  username: deploy
  password: 0608

development:
  <<: *default
  database: test18

test:
  <<: *default
  database: test

production:
  <<: *default
  database: test

staging:
  <<: *default
  database: test18
